site_name: Speedrunapi Docs

nav:
    - Home: 'index.md'
    - 'Working with the library':
        - 'Instalation': 'instalation.md'
        - 'Translation': 'translation.md'
        - 'Users': 'user.md'
        - 'Games': 'game.md'
        - 'Runs': 'runs.md'
        - 'Levels': 'levels.md'
        - 'Regions': 'regions.md'

theme:
    name: readthedocs