site_name: Speedrunapi Docs
nav:
    - Home: 'index.md'
    - 'Working with the library':
        - 'Instalation': 'instalation.md'
        - 'Users': 'user.md'
        - 'Games': 'game.md'
        - 'Runs': 'runs.md'
        - 'Translation': 'translation.md'
theme:
    name: readthedocs